### ISSUE TITLE
Last todo list

### ISSUE THREAD

**Issue by leo-xliu** [kevin-ink/urf#47]
**Ignore this issue**

### TODO

- [x] 1. Make spider move throughout the timer
- [x] 2. Make the white bordered grass smaller/less visible 
- [x] 3. Add more grass (its a nice touch!)
- [x] 4. Add a slightly darker background/ or lighter
- [x] 5. Point message system for kevin (vary directly with points and accuracy and inversely with time)
- [ ] 6. Make the final point increment exponential so it goes faster
- [x] 7. Add additional pillars to the background
